# The manifest for the "{{.Name}}" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: {{.Name}}

# The version of the schema used in this template.
version: {{.Version}}

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: {{.Source.ProviderName}}
  # Additional properties that further specify the location of the artifacts.
  properties:{{range $key, $value := .Source.Properties}}
    {{$key}}: {{$value}}{{end}}
    {{- if .Source.IsCodeStarConnection}}
    # Optional: specify the name of an existing CodeStar Connections connection.
    connection_name: prisidio-global-connection
    {{- end}}
    output_artifact_format: CODEBUILD_CLONE_REF
{{$length := len .Stages}}{{if gt $length 0}}
# This section defines the order of the environments your pipeline will deploy to.
stages:{{range .Stages}}
    - # The name of the environment.
      name: {{.Name}}
      # Optional: flag for manual approval action before deployment.
      {{if not .RequiresApproval }}# {{end}}requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

      # PRISIDIO-CUSTOM
      # Optional: use pre_deploy_code_builds or post_deploy_code_builds to link code builds in pipelines stages
      #           code_builds_service_role is a service role used by specified code builds that trusts this pipeline.
      #           Ensure below code build pipelines and roles deployed before running 'pipeline update' command
      # pre-deploy tests are tests run inside pipeline but do not need additional permissions (e.g. access dynamo). If such tests exist, enable below stage.
#      pre_deploy_code_builds:{{range $buildName := .PreDeployCodeBuilds}}
#        - {{$buildName}}{{end}}
      # Uncomment below if post-deploy exists
#      post_deploy_code_builds:{{range $buildName := .PostDeployCodeBuilds}}
#        - {{$buildName}}{{end}}
      # Uncomment below if either pre/post deploy is specified
#      code_builds_service_role: {{.CodeBuildsServiceRole}}
{{end}}{{end}}
